[package]
name = "img-to-byte-array"
version = "0.1.0"
authors = ["KENTARO OKUDA <lonesometraveler@mac.com>"]
edition = "2018"

[lib]
name = "img2bytes"
path = "src/img2bytes.rs"

[dependencies]
image = "0.22.3"
